"""Add username default value

Revision ID: 0a9f7f572a01
Revises: [auto_generated]
Create Date: 2025-07-05 21:23:40.155735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9f7f572a01'
down_revision: Union[str, Sequence[str], None] = '[auto_generated]'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('esprit', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('esprit_base', 'base_atk',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('esprit_base', 'base_def',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('esprit_base', 'base_hp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('esprit_base', 'equipped_relics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('player', 'total_attack_power',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('player', 'total_defense_power',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('player', 'total_hp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('player', 'last_daily_reward')
    op.drop_column('player', 'power_last_calculated')
    op.drop_column('player', 'shop_purchase_history')
    op.alter_column('player_class', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_player_class_class_type'), table_name='player_class')
    op.drop_index(op.f('ix_player_class_selected_at'), table_name='player_class')
    op.drop_constraint(op.f('player_class_player_id_key'), 'player_class', type_='unique')
    op.drop_index(op.f('ix_player_class_player_id'), table_name='player_class')
    op.create_index(op.f('ix_player_class_player_id'), 'player_class', ['player_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_class_player_id'), table_name='player_class')
    op.create_index(op.f('ix_player_class_player_id'), 'player_class', ['player_id'], unique=False)
    op.create_unique_constraint(op.f('player_class_player_id_key'), 'player_class', ['player_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_player_class_selected_at'), 'player_class', ['selected_at'], unique=False)
    op.create_index(op.f('ix_player_class_class_type'), 'player_class', ['class_type'], unique=False)
    op.alter_column('player_class', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('player', sa.Column('shop_purchase_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('power_last_calculated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('last_daily_reward', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('player', 'total_hp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('player', 'total_defense_power',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('player', 'total_attack_power',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('esprit_base', 'equipped_relics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('esprit_base', 'base_hp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('esprit_base', 'base_def',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('esprit_base', 'base_atk',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('esprit', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
