"""Initial database schema

Revision ID: 25786711e7ad
Revises: 
Create Date: 2025-06-18 07:01:32.090873

"""
from typing import Sequence, Union
from sqlmodel.sql.sqltypes import AutoString
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25786711e7ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('username', AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('nyxies', sa.Integer(), nullable=False),
    sa.Column('erythl', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('fragments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_discord_id'), 'player', ['discord_id'], unique=True)
    op.create_table('esprit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('element', AutoString(), nullable=False),
    sa.Column('awakening_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esprit_owner_id'), 'esprit', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esprit_owner_id'), table_name='esprit')
    op.drop_table('esprit')
    op.drop_index(op.f('ix_player_discord_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
