"""Add stamina system and skill allocation

Revision ID: 3d4f29c0cf73
Revises: ff7556b6938e
Create Date: 2025-06-22 14:10:00.752290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d4f29c0cf73'
down_revision: Union[str, Sequence[str], None] = 'ff7556b6938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: op.alter_column('esprit', 'element', nullable=True)
    op.add_column('player', sa.Column('stamina', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('player', sa.Column('max_stamina', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('player', sa.Column('last_stamina_update', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('player', sa.Column('total_jijies_earned', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('total_erythl_earned', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('total_energy_spent', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('total_stamina_spent', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('skill_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('allocated_skills', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default='{"energy": 0, "stamina": 0, "attack": 0, "defense": 0}'))
    op.add_column('player', sa.Column('skill_reset_count', sa.Integer(), nullable=False, server_default='0'))
    # REMOVED: op.alter_column('player', 'discord_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: op.alter_column('player', 'discord_id', nullable=False)
    op.drop_column('player', 'skill_reset_count')
    op.drop_column('player', 'allocated_skills')
    op.drop_column('player', 'skill_points')
    op.drop_column('player', 'total_stamina_spent')
    op.drop_column('player', 'total_energy_spent')
    op.drop_column('player', 'total_erythl_earned')
    op.drop_column('player', 'total_jijies_earned')
    op.drop_column('player', 'last_stamina_update')
    op.drop_column('player', 'max_stamina')
    op.drop_column('player', 'stamina')
    # REMOVED: op.alter_column('esprit', 'element', nullable=False)
    # ### end Alembic commands ###