"""add_pending_building_income_field

Revision ID: 79b5cf31f729
Revises: babf213f6ccf
Create Date: 2025-07-08 03:01:13.794132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b5cf31f729'
down_revision: Union[str, Sequence[str], None] = 'babf213f6ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'player',
        sa.Column('pending_building_income', sa.Integer(), nullable=False, server_default='0')
    )
    # Optionally remove server default to keep the schema clean
    op.alter_column('player', 'pending_building_income', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'pending_building_income')
    # ### end Alembic commands ###
