"""Fix discord_id to BigInteger

Revision ID: ac5e4c8d6205
Revises: 65829661cf99
Create Date: 2025-06-18 07:30:16.812497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac5e4c8d6205'
down_revision: Union[str, Sequence[str], None] = '65829661cf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'discord_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_player_discord_id'), table_name='player')
    # We now give the unique constraint a specific name.
    op.create_unique_constraint(op.f('uq_player_discord_id'), 'player', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We use the same name here to drop the constraint.
    op.drop_constraint(op.f('uq_player_discord_id'), 'player', type_='unique')
    op.create_index(op.f('ix_player_discord_id'), 'player', ['discord_id'], unique=True)
    op.alter_column('player', 'discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
