"""Add EspritBase table and link to Esprit

Revision ID: b8028f40a48e
Revises: ac5e4c8d6205
Create Date: 2025-06-18 08:18:09.693726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b8028f40a48e'
down_revision: Union[str, Sequence[str], None] = 'ac5e4c8d6205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espritbase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('element', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore
    sa.Column('base_tier', sa.Integer(), nullable=False),
    sa.Column('portrait_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.Column('full_body_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_espritbase_slug'), 'espritbase', ['slug'], unique=True)
    op.add_column('esprit', sa.Column('esprit_base_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'esprit', 'espritbase', ['esprit_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'esprit', type_='foreignkey') # type: ignore
    op.drop_column('esprit', 'esprit_base_id')
    op.drop_index(op.f('ix_espritbase_slug'), table_name='espritbase')
    op.drop_table('espritbase')
    # ### end Alembic commands ###
