"""remove_type_system

Revision ID: cdfc6407423d
Revises: 25acabec9bd3
Create Date: 2025-06-23 08:57:25.307857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfc6407423d'
down_revision: Union[str, Sequence[str], None] = '25acabec9bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esprit_base_type'), table_name='esprit_base')
    op.drop_index(op.f('ix_espritbase_type_tier'), table_name='esprit_base')
    op.drop_column('esprit_base', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esprit_base', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_espritbase_type_tier'), 'esprit_base', ['type', 'base_tier'], unique=False)
    op.create_index(op.f('ix_esprit_base_type'), 'esprit_base', ['type'], unique=False)
    # ### end Alembic commands ###
