"""initial migration

Revision ID: f389200b0e55
Revises: 
Create Date: 2025-06-18 15:18:31.851032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f389200b0e55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('last_energy_update', sa.DateTime(), nullable=False),
    sa.Column('nyxies', sa.Integer(), nullable=False),
    sa.Column('erythl', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('fragments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_discord_id'), 'player', ['discord_id'], unique=True)
    
    op.create_table('esprit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('esprit_base_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('awakening_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['esprit_base_id'], ['espritbase.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esprit_awakening_level'), 'esprit', ['awakening_level'], unique=False)
    op.create_index(op.f('ix_esprit_created_at'), 'esprit', ['created_at'], unique=False)
    op.create_index(op.f('ix_esprit_element'), 'esprit', ['element'], unique=False)
    op.create_index(op.f('ix_esprit_esprit_base_id'), 'esprit', ['esprit_base_id'], unique=False)
    op.create_index(op.f('ix_esprit_owner_id'), 'esprit', ['owner_id'], unique=False)
    op.create_index(op.f('ix_esprit_tier'), 'esprit', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esprit_tier'), table_name='esprit')
    op.drop_index(op.f('ix_esprit_owner_id'), table_name='esprit')
    op.drop_index(op.f('ix_esprit_esprit_base_id'), table_name='esprit')
    op.drop_index(op.f('ix_esprit_element'), table_name='esprit')
    op.drop_index(op.f('ix_esprit_created_at'), table_name='esprit')
    op.drop_index(op.f('ix_esprit_awakening_level'), table_name='esprit')
    op.drop_table('esprit')
    op.drop_index(op.f('ix_player_discord_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
