"""Remove space logic and update to unified constants

Revision ID: ff7556b6938e
Revises: b0a46dea8fa4
Create Date: 2025-06-21 21:36:45.634768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7556b6938e'
down_revision: Union[str, Sequence[str], None] = 'b0a46dea8fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('esprit', 'space_per_unit')
    op.drop_column('esprit', 'total_space')
    op.drop_column('player', 'current_space')
    op.drop_column('player', 'max_space')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('max_space', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('current_space', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('esprit', sa.Column('total_space', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('esprit', sa.Column('space_per_unit', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
